# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeixinUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50, verbose_name='openid')),
                ('unionid', models.CharField(default='', max_length=50, verbose_name='uuid')),
                ('session_key', models.CharField(default='', max_length=50)),
                ('sid', models.UUIDField(default=uuid.uuid1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'ordering': ['-pk'],
                'get_latest_by': 'pk',
            },
        ),
    ]
