# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=15, verbose_name='电影ID')),
                ('title', models.CharField(max_length=50, verbose_name='电影中文名')),
                ('link', models.CharField(max_length=100, verbose_name='电影地址')),
                ('rating', models.CharField(max_length=10, verbose_name='电影评分')),
                ('comment', models.CharField(max_length=100, verbose_name='电影评论')),
                ('year', models.CharField(max_length=10, verbose_name='电影上映年份')),
                ('directors', models.CharField(max_length=20, verbose_name='电影导演')),
                ('casts', models.CharField(max_length=20, verbose_name='电影演员')),
                ('images', models.CharField(max_length=50, verbose_name='电影海报')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
