# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='casts',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='电影演员'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='电影评论'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='电影导演'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='images',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电影海报'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='电影地址'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='电影评分'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电影中文名'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='电影上映年份'),
        ),
    ]
