# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0002_auto_20171113_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='images',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='电影海报'),
        ),
    ]
