# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0003_auto_20171113_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='casts',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='电影演员'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电影导演'),
        ),
    ]
