# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0005_movie_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.IntegerField(blank=True, null=True, verbose_name='电影评星'),
        ),
    ]
