# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0006_auto_20171114_1711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Top',
        ),
    ]
