# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0008_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ratings_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='评价人数'),
        ),
    ]
