# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0010_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='users',
            new_name='user',
        ),
    ]
