# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-06 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0011_auto_20180412_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='InTheaters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=15, verbose_name='电影ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='电影中文名')),
                ('countries', models.CharField(blank=True, max_length=20, null=True, verbose_name='上映城市')),
                ('genres', models.CharField(blank=True, max_length=20, null=True, verbose_name='电影类型')),
                ('rating', models.CharField(blank=True, max_length=10, null=True, verbose_name='电影评分')),
                ('year', models.CharField(blank=True, max_length=10, null=True, verbose_name='电影上映年份')),
                ('directors', models.CharField(blank=True, max_length=50, null=True, verbose_name='电影导演')),
                ('casts', models.CharField(blank=True, max_length=100, null=True, verbose_name='电影演员')),
                ('images', models.CharField(blank=True, max_length=150, null=True, verbose_name='电影海报')),
                ('stars', models.IntegerField(blank=True, null=True, verbose_name='电影评星')),
                ('ratings_count', models.IntegerField(blank=True, null=True, verbose_name='评价人数')),
                ('summary', models.CharField(blank=True, max_length=1000, null=True, verbose_name='电影简介')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
