# Generated by Django 2.2.11 on 2020-07-12 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0012_intheaters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intheaters',
            options={'ordering': ['id']},
        ),
    ]
