dev-build:
	docker-compose -f ./docker-compose-dev.yml build

dev-up-d:
	docker-compose -f ./docker-compose-dev.yml up -d

dev-up:
	docker-compose -f ./docker-compose-dev.yml up

dev-down:
	docker-compose -f ./docker-compose-dev.yml down
